name: Parallel Cypress Tests

on: [push]

jobs:
  test:
    name: Cypress Cloud Tests - First Iteration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Parallel Tests
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
          group: XpehnoAutomation
          spec: "cypress/Integration/Examples/Candiate search1.js"
          ci-build-id: "${{ github.run_id }}-${{ matrix.containers }}"
          
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_second_iteration:
    name: Cypress Cloud Tests - Second Iteration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Parallel Tests (Second Iteration)
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
          group: XpehnoAutomation
          spec: "cypress/Integration/Examples/Candiate search1.js"
          ci-build-id: "${{ github.run_id }}-${{ matrix.containers }}"
          
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
